   [build]
   builder = "NIXPACKS"
   buildCommand = "cd frontend && npm install && npm run build"
   
   [deploy]
   startCommand = "python main.py & cd frontend && npm run start"
   healthcheckPath = "/"
   restartPolicyType = "ON_FAILURE"
   numReplicas = 1
   
   [env]
   PYTHON_VERSION = "3.8"
   NODE_VERSION = "16.x"

   [build.args]
   PYTHON_VERSION = "3.8"