[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "" 
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[env]
PYTHON_VERSION = "3.9"
NODE_VERSION = "18.x"

[[build.env]]
name = "NIXPACKS_NODE_VERSION"
value = "18.x"

[[build.env]]
name = "NIXPACKS_PYTHON_VERSION"
value = "3.8"