   [build]
   builder = "NIXPACKS"
   buildCommand = """
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&\
    apt-get install -y nodejs &&\
    cd frontend && npm install && npm run build &&\
    pip install -r requirements.txt
"""
   
   [deploy]
   startCommand = "python main.py & cd frontend && npm run start"
   healthcheckPath = "/"
   restartPolicyType = "ON_FAILURE"
   numReplicas = 1
   
   [env]
   PYTHON_VERSION = "3.8"
   NODE_VERSION = "18.x"

   [build.args]
   PYTHON_VERSION = "3.8"
   NODE_VERSION = "18.x"